version: '3.7'

services:
  my-app:
    container_name: github-vue
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8080'
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
