name: CI/CD Practice

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      #- name: create droplet
        #run: doctl compute droplet create --image ubuntu-20-04-x64 --size s-1vcpu-1gb --region nyc1 CI-CD-Github
        
      - name: Install SSH Key
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          username: ${{ secrets.USERNAME }}
          script: |
            ls
            if [ ! -d "vue-github" ] ; then
              git clone https://github.com/amirhamza05/vue-github
            fi
            cd vue-github
            git pull
            bash deploy.sh
